# Generated by Django 5.2 on 2025-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=18)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Jugador'), (3, 'Desarrollador')])),
                ('terminos', models.BooleanField(default=False)),
            ],
        ),
    ]
