# Generated by Django 5.2 on 2025-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Jugador'), (3, 'Desarrollador')], default=2),
        ),
    ]
