# Generated by Django 5.2 on 2025-04-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registro_direccion_alter_registro_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='terminos',
        ),
    ]
