# Generated by Django 5.2 on 2025-05-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiaJuego',
            fields=[
                ('id_juego', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
