# Generated by Django 5.2 on 2025-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_copiajuego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copiajuego',
            old_name='nombre',
            new_name='nombre_juego',
        ),
        migrations.AlterField(
            model_name='copiajuego',
            name='id_juego',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
