# Generated by Django 5.2 on 2025-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nombre_copiajuego_nombre_juego_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copiajuego',
            old_name='id_juego',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='copiajuego',
            name='nombre_juego',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
