# Generated by Django 5.2 on 2025-05-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_juego_copiajuego_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='nombre_juego',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
