# Generated by Django 5.2 on 2025-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_juego_nombre_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasSugerido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
